using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AllinLobby.Entity.Enums
{
    public enum Country
    {
        Adana = 0,
        Adıyaman = 1,
        Afyon = 2,
        Ağrı = 3,
        Amasya = 4,
        Ankara = 5,
        Antalya = 6,
        Artvin = 7,
        Aydın = 8,
        Balıkesir = 9,
        Bilecik = 10,
        Bingöl = 11,
        Bitlis = 12,
        Bolu = 13,
        Burdur = 14,
        Bursa = 15,
        Çanakkale = 16,
        Çankırı = 17,
        Çorum = 18,
        Denizli = 19,
        Diyarbakır = 20,
        Edirne = 21,
        Elazığ = 22,
        Erzincan = 23,
        Erzurum = 24,
        Eskişehir = 25,
        Gaziantep = 26,
        Giresun = 27,
        Gümüşhane = 28,
        Hakkari = 29,
        Hatay = 30,
        Isparta = 31,
        Mersin = 32,
        İstanbul = 33,
        İzmir = 34,
        Kars = 35,
        Kastamonu = 36,
        Kayseri = 37,
        Kırklareli = 38,
        Kırşehir = 39,
        Kocaeli = 40,
        Konya = 41,
        Kütahya = 42,
        Malatya = 43,
        Manisa = 44,
        Kahramanmaraş = 45,
        Mardin = 46,
        Muğla = 47,
        Muş = 48,
        Nevşehir = 49,
        Niğde = 50,
        Ordu = 51,
        Rize = 52,
        Sakarya = 53,
        Samsun = 54,
        Siirt = 55,
        Sinop = 56,
        Sivas = 57,
        Tekirdağ = 58,
        Tokat = 59,
        Trabzon = 60,
        Tunceli = 61,
        Şanlıurfa = 62,
        Uşak = 63,
        Van = 64,
        Yozgat = 65,
        Zonguldak = 66,
        Aksaray = 67,
        Bayburt = 68,
        Karaman = 69,
        Kırıkkale = 70,
        Batman = 71,
        Şırnak = 72,
        Bartın = 73,
        Ardahan = 74,
        Iğdır = 75,
        Yalova = 76,
        Karabük = 77,
        Kilis = 78,
        Osmaniye = 79,
        Düzce = 80
    }

}

